networks:
  dev:

volumes:
  certbot-www:     # для ACME-вызовов
  certbot-conf:    # для хранения сертификатов

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - 'certbot-www:/var/www/certbot:ro'
      - '/etc/letsencrypt:/etc/letsencrypt:ro'
      - './empty.conf:/etc/nginx/conf.d/default.conf'   # подмена дефолтного конфига пустым файлом
    depends_on:
      - backend
      - frontend
    networks:
      - dev
    restart: unless-stopped

#  certbot:
#    image: certbot/certbot:latest
#    volumes:
#      - 'certbot-www:/var/www/certbot:rw'
#      - 'certbot-conf:/etc/letsencrypt:rw'
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
#    networks:
#      - dev
#    # Не публикуем порты, только внутренняя сеть

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    networks:
      - dev
    volumes:
      - ./backend/instance:/instance
      - ./backend/system_prompt.txt:/system_prompt.txt
    environment:
      - FLASK_APP=run:create_app
      - YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}
      - YOOKASSA_SECRET_KEY=${YOOKASSA_SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - GIGA_KEY=${GIGA_KEY}
      - SALUTE_KEY=${SALUTE_KEY}
      - GIGACHAT_CREDENTIALS=${GIGACHAT_CREDENTIALS}
      - GIGACHAT_SCOPE=${GIGACHAT_SCOPE:-GIGACHAT_API_PERS}
      - GIGACHAT_VERIFY_SSL_CERTS=${GIGACHAT_VERIFY_SSL_CERTS:-False}
      - SYSTEM_PROMPT_PATH=/system_prompt.txt
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_CONFIG=${FLASK_CONFIG:-production}
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=${FRONTEND_URL:-https://nikamentalhelth.ru}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    networks:
      - dev
    restart: unless-stopped