user  nginx;  # лучше использовать nginx вместо root для безопасности
worker_processes  1;

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=10s;  # DNS Docker'а

    server {
        listen 80;
        server_name nikamentalhelth.ru www.nikamentalhelth.ru;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }
}