user  root;
worker_processes  1;
events {
    worker_connections 1024;
}
http {
    server {
        listen 80;
        server_name nikamentalhelth.ru www.nikamentalhelth.ru;

        location /.well-known/acme-challenge/ {
            alias /var/www/certbot/.well-known/acme-challenge/;
        }

        location / {
            return 200 'OK';
            add_header Content-Type text/plain;
        }
    }
}