"""add new fields to users

Revision ID: 27210995ddb4
Revises: 044680e2b0cc
Create Date: 2026-02-21 20:35:29.501428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27210995ddb4'
down_revision: Union[str, Sequence[str], None] = '044680e2b0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'created_on')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_on', sa.DATETIME(), nullable=True))
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
